bert_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'), # 127.0.0.1:8000/
    path('predict_sentiment/', include('main.urls')), # 127.0.0.1:8000/predict_sentiment/
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [ 
    # 127.0.0.1:8000/predict_sentiment/bert_input/
    path('bert_input/', views.bert_input, name='bert_input'),
    path('bert_predict/', views.bert_predict, name='bert_predict'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.utils import timezone
from django.conf import settings

import pandas as pd
from . import inference_bert
from . import bert_load

def index(request):
    current_time = timezone.now()

    context = {'current_time':current_time}

    return render(request, 'main/index.html', context)


def bert_input(request):
    # reviews_df = pd.read_table('./data/naver_shopping.txt', names=['ratings', 'reviews'])
    reviews_df = pd.read_table(settings.DATA_ROOT + '/naver_shopping.txt', names=['ratings', 'reviews'])
    reviews_df = reviews_df.drop_duplicates('reviews')
    reviews_df = reviews_df.reset_index(drop=True)
    reviews_df['label'] = reviews_df['ratings'].apply(lambda x : 1 if x > 3 else 0)
    reviews_df = reviews_df.head()

    reviews_df_html = reviews_df.to_html(
        columns=['reviews', 'label'],
        index=False, na_rep="", bold_rows=True,
        classes=["table", "table-hover", "table-processed"])

    context = {'reviews_df_html':reviews_df_html}
    return render(request, 'main/bert_input.html', context)


def bert_predict(request):

    target_sentence = request.POST['target_sentence']

    # tokenizer = settings.TOKENIZER_KOBERT
    # model = settings.MODEL_KOBERT
    tokenizer = bert_load.load_bert_tokenizer()
    model = bert_load.create_bert_model()

    result_bert = inference_bert.predict_sentiment(target_sentence, tokenizer, model)

    context = {'target_sentence':target_sentence,
                'result_bert':result_bert}

    return render(request, 'main/bert_predict.html', context)

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <title>Sentiment-analysis</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/custom_style.css' %}" />
  </head>

  <body>

    {% block content_1 %}
    {% endblock %}
    
  </body>
</html>

main/templates/main/bert_input.html
{% extends 'main/base.html' %}

{% block content_1 %}

  <div style='text-align:center;'>

    <h1 id='page_title'>
      Sentiment analysis using KoBERT
    </h1>
  
    <form action="{% url 'main:bert_predict' %}" method="POST" class="main-form">
      {% csrf_token %}
  
      <h2 style='width:50%; margin:auto;'>감정 분석을 위한 문장을 적어주세요! </h2><br>
  
      <textarea name="target_sentence" style="width: 30%; height: 5em;"
        placeholder="ex) 이거 살까말까 고민 많이 했는데 정작 써보니 나쁘지 않네요 곧 재구매 예정입니다!">
      </textarea><br>
  
      <input type="submit" value='Your sentiment counts!' id='input_submit'></input>
  
    </form>
  
    <div style="width:50%; margin:auto; padding-top:4em;">
      <p style='text-align: left; margin-left:2.5em; margin-bottom: 0.5em;'> Used dataset : </p>
      {{ reviews_df_html | safe }}
    </div>
  
  </div>
  
  <div id='nav_foot'>
    <h2><a href="{% url 'index' %}">Return to home</a></h2>
  </div>

{% endblock %}

main/templates/main/bert_predict.html
{% extends 'main/base.html' %}

{% block content_1 %}

  <div style='text-align:center;'>

    <h1 id='page_title'>
      Sentiment analysis result - KoBERT
    </h1>
  
    <hr>
  
    <h2 class='semi-headline'>Target review : </h2><br>
    <p class='result_p'>{{ target_sentence }}</p>
  
    <hr>
  
    <h2 class='semi-headline'>Analyzed sentiment value : </h2><br>
  
    {% if '긍정' in result_bert %}
      <p class='result_positive'>{{ result_bert }}</p>
    {% else %}
      <p class='result_negative'>{{ result_bert }}</p>
    {% endif %}
  
    <hr>
  
  </div>
  
  <div id='nav_foot'>
    <h2><a href="{% url 'main:bert_input' %}">Return to previous page</a></h2>
    <h2><a href="{% url 'index' %}">Return to home</a></h2>
  </div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content_1 %}

    <div id='index_title'>
        <h1 class='bert_title'>
            <a href="{% url 'main:bert_input' %}"> BERT TEST </a>
        </h1>
        <!-- <h3 style="color:grey;"> {{ current_time }} </h3> -->
    </div>

{% endblock %}